# Generated by Django 4.2.1 on 2024-12-04 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job_seeker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile/default_profile_pic.webp', upload_to=job_seeker.models.profile_image_upload_to)),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_headline', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_summary', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_job_title', models.CharField(blank=True, max_length=225, null=True)),
                ('prefered_job_location', models.CharField(blank=True, max_length=225, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('prefered_job_level', models.CharField(blank=True, max_length=225, null=True)),
                ('prefered_job_type', models.CharField(blank=True, max_length=225, null=True)),
                ('prefered_job_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_career_preference', to='job_seeker.jobseeker')),
            ],
        ),
    ]
