# Generated by Django 4.2.1 on 2024-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_resume_projectdetail_experiencedetail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationdetail',
            unique_together={('user', 'degree_type', 'education_program', 'institute_name')},
        ),
        migrations.AlterUniqueTogether(
            name='experiencedetail',
            unique_together={('user', 'job_title', 'institute_name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectdetail',
            unique_together={('user', 'project_title')},
        ),
    ]
