# Generated by Django 5.1.3 on 2024-12-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_alter_careerpreference_prefered_job_category_and_more'),
        ('jobs', '0002_alter_jobcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpreference',
            name='prefered_job_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory'),
        ),
    ]
