# Generated by Django 4.2.1 on 2024-12-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_alter_educationdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_job_alert', models.BooleanField(default=True)),
                ('job_application_status_alert', models.BooleanField(default=True)),
                ('job_recommendation_alert', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_settings', to='job_seeker.jobseeker')),
            ],
        ),
    ]
