# Generated by Django 4.2.1 on 2024-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_alter_careerpreference_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='total_experience',
            field=models.FloatField(default=0),
        ),
    ]
