# Generated by Django 4.2.1 on 2024-12-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruiter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile_image', models.ImageField(default='profile/default_profile_pic.webp', upload_to=recruiter.models.profile_image_upload_to)),
                ('company_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('company_type', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('website_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
