# Generated by Django 5.1.3 on 2024-12-03 15:32

import django.db.models.deletion
import recruiter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile_image', models.ImageField(default='profile/default_profile_pic.webp', upload_to=recruiter.models.profile_image_upload_to)),
                ('company_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('company_type', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
