# Generated by Django 5.1.3 on 2024-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
