# Generated by Django 4.2.1 on 2024-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_recruiter_company_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
