// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSE31wheyZmqz5dg1qNt2XeXgwIQ-hBc',
    appId: '1:371643432789:web:6e931ed79e287215b7f9dc',
    messagingSenderId: '371643432789',
    projectId: 'merocareer-37e6e',
    authDomain: 'merocareer-37e6e.firebaseapp.com',
    storageBucket: 'merocareer-37e6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppf8EvOPUu4UIJ76CExo8L1OxLdDQvss',
    appId: '1:371643432789:android:68e1df8749868763b7f9dc',
    messagingSenderId: '371643432789',
    projectId: 'merocareer-37e6e',
    storageBucket: 'merocareer-37e6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcAK6w94z6bWFvobBWGPVnk1jUbfIMTUk',
    appId: '1:371643432789:ios:b29c6935f6a96a8bb7f9dc',
    messagingSenderId: '371643432789',
    projectId: 'merocareer-37e6e',
    storageBucket: 'merocareer-37e6e.firebasestorage.app',
    iosBundleId: 'com.example.meroCareer',
  );
}
