# Generated by Django 4.2.1 on 2024-12-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0004_alter_educationdetail_unique_together_and_more'),
        ('jobs', '0002_alter_job_recruiter_alter_requiredskill_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Reviewed', 'Reviewed'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Under Review', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='job_seeker.jobseeker')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
