# Generated by Django 5.1.3 on 2024-12-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
