# Generated by Django 4.2.1 on 2024-12-04 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('no_of_vacancy', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('job_type', models.CharField(max_length=255)),
                ('job_level', models.CharField(max_length=255)),
                ('job_requirement', models.TextField()),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=jobs.models.category_image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='jobs.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_job_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
