# Generated by Django 5.1.3 on 2024-12-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
