# Generated by Django 4.2.1 on 2024-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_recruiter_alter_requiredskill_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
