# Generated by Django 4.2.1 on 2024-12-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_alter_careerpreference_expected_salary_and_more'),
        ('jobs', '0003_job_posted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('searched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searcher', to='job_seeker.jobseeker')),
                ('searched_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_job', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Recent Search',
                'verbose_name_plural': 'Recent Searches',
                'ordering': ['-searched_at'],
                'unique_together': {('searched_by', 'searched_job')},
            },
        ),
    ]
